### PR TITLE
created model for Training_Model.py

### PR DESCRIPTION
**Pull request by binauralbeat**
created my model for Training program

'' 
git fetch --all
git checkout db_creating_models
"
in code make sure model Training_Prog is there.

### CODE REVIEW

**Comment by obscure-shadow** [comment]
need to change either
1. ``` prog_name``` to ``` name ```

or

1. ``` return f'{self.name}' ``` to  ``` return f'{self.prog_name}'```

probably number 2.

**Comment by obscure-shadow** [comment]
looks good now :shipit:

**Comment by MrErin** [comment]
You'll need to make your Charfields have numeric lengths.  It needs to be this:
models.CharField(max_length=50)

not this:
models.CharField(max_length="50")

**Comment by MrErin** [comment]
beautiful! 🥇

**Pull request merged**
