### PR TITLE
JS - Created many to many field on employee & fixed url pattern paths

### PR DESCRIPTION
**Pull request by jacobxcodes**
## Link to Ticket

Autolink format: hashtag and number, ex: #1094

Closes #
Doesn't close a ticket

## Description of Proposed Changes
1. Ticket refactors models to include a many to many on the employee model
1. Deleted employee_training joining table model
1. Added forward slash to bangazon2 urls and removed forward slashes on WorkforceManagement urls

##### New Employee Model
```
class Employee(models.Model):
    """
    Model for Employee Table contains department_id, computer_id, is_supervisor, name, & start_date
    """
    training = models.ManyToManyField('Training_Prog')
    department = models.ForeignKey('Department', on_delete=models.CASCADE)
    computer = models.ForeignKey('Computer', on_delete=models.CASCADE)
    is_supervisor = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    start_date = models.DateField(auto_now_add=True)

    def __str__(self):

        return f'{self.name}'
```
##### Outline the steps to test
1. Make sure you're on master
1. Fetch and check out to branch
1. Run virtual machine
1. Run any migrations you need
1. Run server
```
Note: No distinct visible changes are made but migrations have changed.
```

```
git fetch --all
git checkout js_refact_many
```

##### Modified

	WorkforceManagement/models/Department_Model.py
	WorkforceManagement/models/Employee_Model.py
	WorkforceManagement/models/Training_Model.py
	WorkforceManagement/urls.py
	bangazon2/urls.py

##### Deleted

	WorkforceManagement/models/Emp_Training_Model.py

##### Added 

	WorkforceManagement/migrations/0002_employee_training.py

## Mentions @username
@binauralbeat @obscure-shadow @CashewRose @MrErin 
Tag users that need to review this code

## Testing
No testing was done on this application

* [ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
* [ ] I certify that all existing tests pass
* [ ] The README has been updated with complete information
* [ ] All classes and functions have docstrings
* [ ] All file names match class and describe use (ex: Employee_Model.py, Employee_View.py)

## Deploy Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Definition of Done

1. The project must be fully documented. This includes the following:
   1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
   1. Every class must be documented with purpose, author, and methods.
   1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
1. Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each

### CODE REVIEW

**Comment by kimberly-bird** [comment]
Looks good! I'm not 100% if it matters if the quotes around 'Training_Prog' are needed: `training = models.ManyToManyField('Training_Prog')` 

See this doc: https://docs.djangoproject.com/en/2.1/topics/db/examples/many_to_many/#many-to-many-relationships

**Comment by MrErin** [comment]
Need to add a docstring including author to Employee_List_View

I expect to see two separate commits for these changes.

**Comment by jacobxcodes** [comment]
@kimberly-bird I went into the many to many field and removed the quotes and it threw a fit. Does it make a big difference that it's in quotes? Will this affect any thing down the line?

**Comment by kimberly-bird** [comment]
@JacobAndrewSmith92 if it threw a fit, then keep the quotes :)

**Comment by obscure-shadow** [comment]
looks good to me minus the things mentioned above

**Comment by MrErin** [comment]
You should be committed. 👍

**Comment by jacobxcodes** [comment]
@kimberly-bird No fits needed here.

**Pull request merged**
