### PR TITLE
Db templates

### PR DESCRIPTION
**Pull request by binauralbeat**
## Link to Ticket

#9 
Closes #
#9 
## Description of Proposed Changes
user can add training programs
## Steps to Test

```sh
git fetch --all
git checkout db_templates
```

Open in the browser, click training programs, create a new program, enter a program of your choosing.
After creating a program go back to training program list and verify that your program is listed.

### CODE REVIEW

**Comment by obscure-shadow** [comment]
works for me :shipit:

**Comment by jacobxcodes** [comment]
:shipit:

**Comment by CashewRose** [comment]
Can't make a start and date or assign one. But it auto makes them for the exact time you make a new training program.

**Comment by CashewRose** [comment]
Also need testing before we can close the ticket.

**Pull request merged**
